spring:
  application:
    name: catalogue-service-spring
#  profiles:
#   active: development
#  cloud:
#    config:
#      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
server:
  port : 9010
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger